name: Role
module: Admin
description: Role-based permissions
ui:
  show_in_sidebar: true
  icon: shield
  default_view: dashboard
views:
- name: Dashboard
  type: summary
  id: summary
- name: Users
  type: association
  target: User
  id: association
- name: Audit Trail
  type: history
  id: history
fields:
- name: name
  label: Name
  type: String
  required: true
- name: permissions
  label: Permissions
  type: JSON
  default: '[]'
  required: true
slug: role
permission_namespace: role
table_name: roles
