"""auto_sync_blueprints_humans_raja

Revision ID: 4684846099a3
Revises: a18ca1b39029
Create Date: 2026-03-06 08:49:20.878486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4684846099a3'
down_revision: Union[str, Sequence[str], None] = 'a18ca1b39029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humanss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humanss_id'), 'humanss', ['id'], unique=False)
    op.create_table('rajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cast', sa.String(), nullable=True),
    sa.Column('old', sa.String(), nullable=True),
    sa.Column('how', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rajas_id'), 'rajas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rajas_id'), table_name='rajas')
    op.drop_table('rajas')
    op.drop_index(op.f('ix_humanss_id'), table_name='humanss')
    op.drop_table('humanss')
    # ### end Alembic commands ###
